### ISSUE TITLE
Nested structure verification fail

### ISSUE THREAD

**Issue by janmichek** [aeternity/smart-contract-verifier#44]
When verifying multiple file contracts in nested structure it will cause a fail

https://github.com/aeternity/smart-contract-verifier/assets/15363559/ed042037-772f-4752-b3dc-5542436640b4

I am attaching 2 examples of successful multiple file verification

1. multiple file drop

https://github.com/aeternity/smart-contract-verifier/assets/15363559/c42b9d54-99f5-441a-bce9-c4957ffb2689

2. folder drop

https://github.com/aeternity/smart-contract-verifier/assets/15363559/37f92127-3d8b-4ad1-8bc8-61d4735d1202

For deploying multiple file contract, you can use my simple app
https://github.com/aeternity/multiple-file-contract-deployer

**Comment by lukeromanowicz** [comment]
Thanks for reporting the issue. I wasn't able to test it with your exact setup because the referenced PR in aescan repo doesn't support directory upload (all files are submitted as they were in the root directory). I created my own test setup in [this fiddle](https://jsfiddle.net/p5z9huv2/) and fixed in commit 8bbb97b955.
 
It will be released as version 1.0.1 today.

**Comment by lukeromanowicz** [comment]
Released and deployed to production in 1.0.1 release

**Comment by janmichek** [comment]
> Thanks for reporting the issue. I wasn't able to test it with your exact setup because the referenced PR in aescan repo doesn't support directory upload (all files are submitted as they were in the root directory). I created my own test setup in [this fiddle](https://jsfiddle.net/p5z9huv2/) and fixed in commit [8bbb97b](https://github.com/aeternity/smart-contract-verifier/commit/8bbb97b955a74c0494ed1a0796d1080cf2d58689).
> 
> ![image](https://private-user-images.githubusercontent.com/46789227/309241505-eea9a9c7-a12b-464d-a245-c46d86e89874.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MjYxNDQsIm5iZiI6MTcwOTUyNTg0NCwicGF0aCI6Ii80Njc4OTIyNy8zMDkyNDE1MDUtZWVhOWE5YzctYTEyYi00NjRkLWEyNDUtYzQ2ZDg2ZTg5ODc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA0MTcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjMTIzZTgyYjNiNTM5Y2FhNDY1ZTE4MGZiY2U1ZDJkNGI2OGMwNDM2NDg5MzExYjgzY2I0ODQwMWMwNTcxOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.foUGn6HY4ThOR_v9iFsIXQITl32fUxD98IfuteS4tCE)
> 
> ![image](https://private-user-images.githubusercontent.com/46789227/309241427-3bc1de35-2698-4e22-91c7-c61cf8d9ff34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MjYxNDQsIm5iZiI6MTcwOTUyNTg0NCwicGF0aCI6Ii80Njc4OTIyNy8zMDkyNDE0MjctM2JjMWRlMzUtMjY5OC00ZTIyLTkxYzctYzYxY2Y4ZDlmZjM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA0MTcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNzZkM2NmZmM2ZGYzMGQyMTc1NjhjZDE4YmM3NjdiYThhMTk5YzM4MWExN2M2MjFlNDliNzA4MjAwMWZjNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TCJtCeEq1JW-FifTz1UYtKZ8gH5vhxUkORK88EQl1gE)
> 
> It will be released as version 1.0.1 today.

Thanks for the fix.

Unfortunately, I can't verify it. The service does not seem to work now. When I try to verify even a simple, file contract, with swagger UI, I only get 'pending' status. Can you check it?

Then - in the referenced PR there is the ability to drag and drop directories as shown on the screen capture.

**Comment by janmichek** [comment]
> Thanks for reporting the issue. I wasn't able to test it with your exact setup because the referenced PR in aescan repo doesn't support directory upload (all files are submitted as they were in the root directory). I created my own test setup in [this fiddle](https://jsfiddle.net/p5z9huv2/) and fixed in commit [8bbb97b](https://github.com/aeternity/smart-contract-verifier/commit/8bbb97b955a74c0494ed1a0796d1080cf2d58689).
> 
> ![image](https://private-user-images.githubusercontent.com/46789227/309241505-eea9a9c7-a12b-464d-a245-c46d86e89874.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDExNTQsIm5iZiI6MTcwOTU0MDg1NCwicGF0aCI6Ii80Njc4OTIyNy8zMDkyNDE1MDUtZWVhOWE5YzctYTEyYi00NjRkLWEyNDUtYzQ2ZDg2ZTg5ODc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA4MjczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiNGU1MmM5MDYyN2I0Y2FhMDhiOTMxNDk2OTkwNWRmZWYzOGI5N2JmZGQ4ZWI4MjQwMDc3NmRiZGFjM2VmNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ay_1T_50d4y02hlw4Gwzfy4dHGc5kn966OfJMhQe44Y)
> 
> ![image](https://private-user-images.githubusercontent.com/46789227/309241427-3bc1de35-2698-4e22-91c7-c61cf8d9ff34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDExNTQsIm5iZiI6MTcwOTU0MDg1NCwicGF0aCI6Ii80Njc4OTIyNy8zMDkyNDE0MjctM2JjMWRlMzUtMjY5OC00ZTIyLTkxYzctYzYxY2Y4ZDlmZjM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA4MjczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4ZmQ4ZDI3NGE2ZjM4YzIyYWM3Y2M1MjQzMmUwMzk1MTZjMTA3MGZiZWI3YjA2YTJhNDIxN2RkYmY4NDgyMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kFif6W8ufQiCFj8e_J-cJ_yMtrRAX7hLGDzCgNtiuIk)
> 
> It will be released as version 1.0.1 today.

Thanks for the fix.

THe case I pointed on now works.

In the referenced PR there is the ability to drag and drop directories as shown on the screen capture.

What's more - the 3rd scenario (screen capture) with directory drop - stopped to work. The fix produced regression.

`Entry file does not match any of the uploaded source files`

**Comment by janmichek** [comment]
solved on FE
